runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22

 env_variables:
  CLOUD_STORAGE_BUCKET: random-numbers1 

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
automatic_scaling:
  min_num_instances: 5
  max_num_instances: 15
  cool_down_period_sec: 80
  cpu_utilization:
    target_utilization: 0.5
service: api
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
