import os
import random
from flask import Flask, jsonify
from google.cloud import storage

# Set the GOOGLE_APPLICATION_CREDENTIALS environment variable
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r"C:\Users\ANNE CREMONA\Downloads\gifted-pulsar-422809-q0-b4d9cc90c98c.json"


app = Flask(__name__)

# Initialize Storage client
storage_client = storage.Client()

bucket_name = 'random-numbers1'
bucket = storage_client.get_bucket(bucket_name)

@app.route('/')
def home():
    return 'Welcome to the Random Number Generator App!'

# Set the number of concurrent instances to run
NUM_INSTANCES = 10

# Set the number of random numbers generated by each instance
NUMBERS_PER_INSTANCE = 1000

# Set the total number of random numbers to generate
TOTAL_NUMBERS = NUM_INSTANCES * NUMBERS_PER_INSTANCE

# Set the range for random numbers
MIN_NUMBER = 0
MAX_NUMBER = 100000


@app.route('/generate_and_store', methods=['GET'])
def generate_and_store():
    total_generated = 0

    for instance_num in range(1, NUM_INSTANCES + 1):
        instance_generated = 0
        for _ in range(NUMBERS_PER_INSTANCE):
            random_number = random.randint(0, 100000)
            instance_generated += 1
            total_generated += 1
            print(f'Instance {instance_num}: Generated random number {random_number}')

        print(f'Instance {instance_num}: Total numbers generated: {instance_generated}')

    print(f'Total numbers generated across all instances: {total_generated}')
    return 'Random numbers generated and stored in the storage bucket.'


@app.route('/get_results', methods=['GET'])
def get_results():
    # Retrieve the list of blobs (random numbers) from the bucket
    blobs = bucket.list_blobs()

    # Find the largest and smallest numbers
    largest_number = 0
    smallest_number = float('inf')
    for blob in blobs:
        random_number = int(blob.name.split('_')[-1].split('.')[0])
        if random_number > largest_number:
            largest_number = random_number
        if random_number < smallest_number:
            smallest_number = random_number

    return jsonify({
        'largest_number': largest_number,
        'smallest_number': smallest_number
    })

if __name__ == '__main__':
    app.run(debug=True)